server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
api.security.token.secret=my-super-secret-key-that-is-very-long-and-secure-for-jwt-generation-123456

# RabbitMQ CloudAMQP Configuration
spring.rabbitmq.addresses=amqps://ruhqbjyh:PDSmkE1l47sgVTnGnf2mjkAqrzSEVJsO@beaver.rmq.cloudamqp.com/ruhqbjyh
broker.queue.email.name=default.email
