server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/ms_email?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ CloudAMQP Configuration
spring.rabbitmq.addresses=amqps://ruhqbjyh:PDSmkE1l47sgVTnGnf2mjkAqrzSEVJsO@beaver.rmq.cloudamqp.com/ruhqbjyh
broker.queue.email.name=default.email
# JavaMailSender Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amabyledev@gmail.com
spring.mail.password=SENHA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
